

%CREATEFIT(PWM,ALTURA,VWIND)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : pwm
%      Y Input : altura
%      Z Output: vwind
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Jul-2018 22:59:28


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( pwm, altura, vwind );

% Set up fittype and options.
ft = fittype( 'poly33' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
figure('position', [50, 50, 800, 500],'Color',[1 1 1])
h = plot( fitresult, [xData, yData], zData );
% legend( h, '','vwind vs. pwm, altura', 'Location', 'NorthEast' );
H=legend('$v_{ar}$ vs. pwm, altura','$u$', '$r$', 'Location', 'northeast', 'Orientation', 'vertical');
set(H, 'Interpreter', 'latex', 'Fontsize', 22);
y=ylabel('Altura (cm)', 'fontsize', 22);
x=xlabel('Tempo (s)', 'fontsize', 22);
z=zlabel('Tempo (c)', 'fontsize', 22);
set(x);
% Label axes
xlabel pwm
ylabel altura
zlabel vwind
grid on


